---
- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ lez_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode: '0664'

- name: Create containers
  community.docker.docker_compose_v2:
    project_src: '{{ lez_service_path }}'
    pull: '{{ compose_pull }}'
    state: '{{ compose_state }}'
    recreate: 'always'
