---
- name: Create sequencer key directories
  file:
    path: '{{ lez_service_conf }}/sequencer/seq-{{ item }}'
    owner: '{{ lez_host_uid }}'
    group: dockremap
    state: directory
    mode: '0775'
  loop: '{{ range(lez_sequencer_count) | list }}'

- name: Create sequencer data directories
  file:
    path: '{{ lez_service_data }}/sequencer/seq-{{ item }}'
    owner: '{{ lez_host_uid }}'
    group: dockremap
    state: directory
    mode: '0775'
  loop: '{{ range(lez_sequencer_count) | list }}'

- name: Create sequencer health check script
  template:
    src: 'check_seq.sh.j2'
    dest: '{{ lez_service_path }}/check_seq.sh'
    owner: 'root'
    group: 'docker'
    mode: '0755'

- name: Write sequencer signing keys
  copy:
    dest: '{{ lez_service_conf }}/sequencer/seq-{{ idx }}/signing_key'
    content: '{{ item.signing_key | b64decode }}'
    owner: '{{ lez_host_uid }}'
    group: dockremap
    mode: '0600'
  loop: '{{ lez_sequencer_keys }}'
  loop_control:
    index_var: idx
  no_log: true

- name: Write sequencer bedrock signing keys
  copy:
    dest: '{{ lez_service_conf }}/sequencer/seq-{{ idx }}/bedrock_signing_key'
    content: '{{ item.bedrock_signing_key | b64decode }}'
    owner: '{{ lez_host_uid }}'
    group: dockremap
    mode: '0600'
  loop: '{{ lez_sequencer_keys }}'
  loop_control:
    index_var: idx
  no_log: true
