---
bootstrap__logrotate_frequency: 'hourly'
bootstrap__logrotate_timer_frequency: '*:0/30'

# Container
logos_node_cont_tag: 'deploy-blockchain-dev'
logos_node_cont_name: 'logos-node'
logos_node_cont_vol: '/docker/{{ logos_node_cont_name }}'
logos_node_conf_path: '{{ logos_node_cont_vol }}/conf'
logos_node_log_level: 'INFO'

# Modules: blockchain only
logos_node_modules: ['liblogos_blockchain_module']
logos_node_module_calls:
  - "liblogos_blockchain_module start /conf/node_config.yaml {{ logos_node_blockchain_deployment }}"

# Blockchain
logos_node_blockchain_deployment: 'devnet'
logos_node_blockchain_peer_response_timeout: 30000
logos_node_public_address: '{{ ansible_default_ipv4.address }}'

# Node identity
logos_node_blockchain_node_key: '{{ lookup("vault", "blockchain/nodekeys", field=hostname) }}'
logos_node_blockchain_blend_signing_key: '{{ lookup("vault", "blockchain/blend-signing", field=hostname) }}'
logos_node_blockchain_blend_zk_key: '{{ lookup("vault", "blockchain/blend-zk", field=hostname) }}'
logos_node_blockchain_funding_pk: '{{ lookup("vault", "blockchain/funding", field=hostname) }}'
logos_node_blockchain_voucher_master_key: '{{ lookup("vault", "blockchain/voucher", field=hostname) }}'
logos_node_blockchain_kms_blend_signing: '{{ lookup("vault", "blockchain/kms-blend-signing", field=hostname) }}'
logos_node_blockchain_kms_funding: '{{ lookup("vault", "blockchain/kms-funding", field=hostname) }}'
logos_node_blockchain_kms_voucher: '{{ lookup("vault", "blockchain/kms-voucher", field=hostname) }}'
logos_node_blockchain_kms_blend_zk: '{{ lookup("vault", "blockchain/kms-blend-zk", field=hostname) }}'

# Ports
logos_node_blockchain_swarm_port: 3000
logos_node_blockchain_blend_port: 3400
logos_node_blockchain_api_port: 8080

# Initial peers (Hetzner seed nodes)
logos_node_blockchain_initial_peers: '{{ logos_node_blockchain_initial_peers_env[stage] }}'
logos_node_blockchain_initial_peers_env:
  dev:
    - '/ip4/65.108.203.235/udp/3000/quic-v1/p2p/12D3KooWNMixUYkNuvXrNwnsmK2ZFRKNm48kF2qqtd9Du7Ls1yQe'
    - '/ip4/65.108.203.235/udp/3001/quic-v1/p2p/12D3KooWMwekH9M34FQXX6jPX4XYyNDgaCw68g4y7hqW2bv4UU9h'
    - '/ip4/65.108.203.235/udp/3002/quic-v1/p2p/12D3KooWEyJNQzmnfWcaRzCBv1ebqXMAWJecnBWmzp2AF6gk28PQ'
    - '/ip4/65.108.203.235/udp/3003/quic-v1/p2p/12D3KooWMrcbQQwT2dpNDiuLUdGESoqR3u2sJ8gAHHo9JPQH7yHb'
  test:
    - '/ip4/65.109.51.37/udp/3000/quic-v1/p2p/12D3KooWL7a8LBbLRYnabptHPFBCmAs49Y7cVMqvzuSdd43tAJk8'
    - '/ip4/65.109.51.37/udp/3001/quic-v1/p2p/12D3KooWPLeAcachoUm68NXGD7tmNziZkVeMmeBS5NofyukuMRJh'
    - '/ip4/65.109.51.37/udp/3002/quic-v1/p2p/12D3KooWKFNe4gS5DcCcRUVGdMjZp3fUWu6q6gG5R846Ui1pccHD'
    - '/ip4/65.109.51.37/udp/3003/quic-v1/p2p/12D3KooWAnriLgXyQnGTYz1zPWPkQL3rthTKYLzuAP7MMnbgsxzR'

logos_otel_rpc_receiver_port: 4319

# Consul
logos_node_consul_success_before_passing: 5
logos_node_consul_failures_before_warning: 2
logos_node_consul_failures_before_critical: 20

# Open Ports
open_ports_list:
  logos-node:
    - { port: '{{ logos_node_blockchain_swarm_port }}', comment: 'blockchain swarm', protocol: 'udp' }
    - { port: '{{ logos_node_blockchain_blend_port }}', comment: 'blockchain blend', protocol: 'udp' }
