---
# Logos Execution Zone
lez_rpc_domain: '{{ stage }}net.lez.logos.co'
lez_explorer_domain: 'explorer.{{ stage }}net.lez.logos.co'
lez_service_name: 'logos-exec-zone-{{ stage }}net'
lez_explorer_cont_port: 8081
lez_sequencer_cont_port: 3040
lez_cont_tag: '{{ lez_cont_tag_map[stage] }}'
lez_cont_tag_map:
  dev:  'v0.2.4'
  test: 'v0.2.4'
lez_blockchain_cont_tag: '{{ lez_blockchain_cont_tag_map[stage] }}'
lez_blockchain_cont_tag_map:
  dev:  '0.2.1-rc.3'
  test: 'testnet'
lez_blockchain_cont_api_port: 8080
lez_blockchain_cont_swarm_port: 3000
lez_blockchain_keystore_config: '{{ lookup("vault", "lez/blockchain", field="keystore") }}'
lez_blockchain_deployment_config: '{{ lookup("ansible.builtin.file", "../files/lez/"+stage+"/blockchain_deployment.yaml") | mandatory }}'
lez_sequencer_config:             '{{ lookup("ansible.builtin.file", "../files/lez/"+stage+"/sequencer_config.json") | mandatory }}'
lez_indexer_config:               '{{ lookup("ansible.builtin.file", "../files/lez/"+stage+"/indexer_config.json") | mandatory }}'
lez_blockchain_initial_peers: '{{ lez_blockchain_initial_peers_map[stage] }}'
lez_blockchain_initial_peers_map:
  dev:
    - '/ip4/65.108.203.235/udp/3000/quic-v1/p2p/12D3KooWNbZTQ86TZ9MrZ2wm6iUFFj25AFTzFLUD7i6XkZHoUzU8'
    - '/ip4/65.108.203.235/udp/3001/quic-v1/p2p/12D3KooWNhXaH4XTX6Pp66NDQZxZpXYQzeruwwraMvTxojz1QXPJ'
    - '/ip4/65.108.203.235/udp/3002/quic-v1/p2p/12D3KooWNTLPg5uYPKgZCDvzyaWNwZNcwVKmfS2bNv52E9L9P7Hf'
    - '/ip4/65.108.203.235/udp/50001/quic-v1/p2p/12D3KooWMULUG8RXC2esnfLcVzGHohf6KNPSswkCKa1mdpXz4tHH'
  test:
    - '/ip4/65.109.51.37/udp/3000/quic-v1/p2p/12D3KooWFrouXfmrR4nsLMtE7wu15DoMJ6VtoUtHinREZCvbWHar'
    - '/ip4/65.109.51.37/udp/3001/quic-v1/p2p/12D3KooWJRGau8M1rjT7R5e4YYsgdFhsMX35nRDtMwCDjxQkXAHz'
    - '/ip4/65.109.51.37/udp/3002/quic-v1/p2p/12D3KooWQXJavMDTRscjauFSgVAB1VLB6Rzpy2uY5SU9Tk7927tb'
    - '/ip4/65.109.51.37/udp/50001/quic-v1/p2p/12D3KooWSQc7CcGtvWDPF1yCbBthFnQjprfCVHmfmNDUrSmqQsU1'

# Certbot
certbot_docker_enabled: true
certbot_admin_email: 'devops@status.im'
certbot_services_to_stop: ['nginx']
certbot_certs:
  - domains:
      - '{{ lez_rpc_domain }}'
      - '{{ lez_explorer_domain }}'

# Nginx
nginx_sites:
  lez_rpc_https:
    - listen 443 ssl
    - server_name {{ lez_rpc_domain }}

    - ssl_certificate     /etc/letsencrypt/live/{{ lez_rpc_domain }}/fullchain.pem
    - ssl_certificate_key /etc/letsencrypt/live/{{ lez_rpc_domain }}/privkey.pem

    - location / {
        proxy_pass http://localhost:{{ lez_sequencer_cont_port }}/;
      }

  lez_explorer_https:
    - listen 443 ssl
    - server_name {{ lez_explorer_domain }}

    - ssl_certificate     /etc/letsencrypt/live/{{ lez_rpc_domain }}/fullchain.pem
    - ssl_certificate_key /etc/letsencrypt/live/{{ lez_rpc_domain }}/privkey.pem

    - location / {
        proxy_pass http://localhost:{{ lez_explorer_cont_port }}/;
      }

# Firewall
open_ports_list:
  nginx:
    - { port: [80, 443], proto: 'tcp', comment: 'Nginx and Certbot' }
  logos-blockchain:
    - { port: '{{ lez_blockchain_cont_swarm_port }}', proto: tcp, comment: 'Logos Blockchain Swarm' }
