- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git

- name: infra-role-open-ports
  src: git@github.com:status-im/infra-role-open-ports.git

- name: infra-role-nginx
  src: git@github.com:status-im/infra-role-nginx.git

- name: infra-role-swap-file
  src: git@github.com:status-im/infra-role-swap-file.git

- name: infra-role-consul-service
  src: git@github.com:status-im/infra-role-consul-service.git

- name: infra-role-systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git

- name: infra-role-certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: 8b5f4ed137e399a33c10b7ffbeaacb6e0c52fcb1

- name: infra-role-postgres-ha
  src: git@github.com:status-im/infra-role-postgres-ha.git
  version: a9408d3fac887343039c867fad3740bd5b3fcce6

- name: infra-role-logos-node
  src: git@github.com:status-im/infra-role-logos-node.git
  version: 28eedb5a59a5a63ee42e6cee00b0aaeed4c02e9e

- name: infra-role-wazuh-agent
  src: git@github.com:status-im/infra-role-wazuh-agent.git
